#
# 
# Copyright (C) 2025 lyin888 <lyin007@gmail.com>
# 
# THIS IS FREE SOFTWARE, LICENSED UNDER GPLv3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for BaiduPCS-Go
LUCI_DEPENDS:=+baidupcs-web +wget +openssl-util
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-baidupcs-web
PKG_VERSION:=1.8
PKG_RELEASE:=8

PKG_MAINTAINER:=lyin888 <lyin007@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
